### ISSUE TITLE
Freelancer

### ISSUE THREAD

**Issue by derricck** [aswin-kevin/libanalyzer#1]
Hello, im trying to find someone able to accept a paid request to add some features to a vscode extension, would like to ask if you are able to?

Detailed info here:
https://www.reddit.com/user/Mickaell28/comments/w0k8at/freelance_vscode_extension/

**Comment by aswin-kevin** [comment]
Hey derrick , 
Is this project repo is yours or you wanted to do something similar to this ?
https://github.com/Gruntfuggly/todo-tree

**Comment by derricck** [comment]
Hello, the project is not mine, I would like to add some features to it as I described in the Reddit post. I don't know much about javascript / vscode extension then I was looking to pay someone for this.

I already asked some people that work with javascript but none of them had experience with vscode extension.
I'm msging you cause i see your extension in the marketplace, sorry!

**Comment by aswin-kevin** [comment]
Can you send a email to aswinrj6067@gmail.com ? we can connect and discuss

**Comment by derricck** [comment]
I have mailed you, thank you!

**Comment by aswin-kevin** [comment]
can you please give me your discard username ?

**Comment by derricck** [comment]
Ilyv#6746

**Comment by aswin-kevin** [comment]
request sent
